version: '3.9'

# This file should only be used to run the app locally with the required infrastructure
services:
  url-shortener-api:
    image: url-shortener-api
    container_name: "url-shortener-api"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "30001:5000"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      App_ConnectionStrings__ApplicationDatabase: "Server=url-shortener-db;Port=5432;Database=UrlShortener;User Id=postgres;Password=my_pg_password;"
      App_Serilog__WriteTo__1__Args__ServerUrl: "http://url-shortener-seq:5341"
      
  url-shortener-db:
    image: postgres
    container_name: "url-shortener-db"
    restart: always
    environment:
      POSTGRES_PASSWORD: "my_pg_password"
    ports:
      - "30002:5432"
  
  url-shortener-seq:
    image: datalust/seq:latest
    container_name: "url-shortener-seq"
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "30003:5341"
      - "30004:80" # Seq ui