version: '3.9'
services:
  url-shortener-api:
    image: url-shortener-api
    build:
      context: .
    ports:
      - "30001:5000"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"

  url-shortener-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "my_pg_password"
    ports:
      - "30002:5432"
  
  url-shortener-seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "30003:5341"
      - "30004:80" # Seq ui