version: '3.9'
services:
  url-shortener-api:
    image: product-catalog-api
    build:
      context: .
      dockerfile: ./devops/docker/Dockerfile
    ports:
      - '30001:5000'
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
  url-shortener-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "my_pg_password"
    ports:
      - "30002:5432"