# @name=CreateUrl
# @no-log
POST http://{{host}}/api/urls HTTP/1.1
Content-Type: application/json

{
  "url": "https://google.pt"
}

###
# @name=GetUrl
# @no-log
GET http://{{host}}/{{shortUrl}} HTTP/1.1
Accept: application/json

###
# @name=Live
# @no-log
GET http://{{host}}/health/live HTTP/1.1
Accept: application/json

###
# @name=Ready
# @no-log
GET http://{{host}}/health/ready HTTP/1.1
Accept: application/json


