on:
    workflow_call:

jobs:
    generate-semver:
      runs-on: ubuntu-latest
      outputs:
        semver: ${{ steps.fullsemver.output.semver }}
      steps:
      - name: ✅ Checkout
        uses: actions/checkout@v3
        
      - name: ⚙️ Generate SemVersion
        id: semver
        uses: paulhatch/semantic-version@v5.3.0
          
      - name: ⚙️ Set SemVersion output
        id: fullsemver
        run: |
          if [ ${{ github.ref_name }} != 'main' ]; then
            echo "semver=${{ steps.semver.outputs.version }}-${{ github.run_id }}.${{ github.run_number }}" >> "$GITHUB_OUTPUT"
          else
            echo "semver=${{ steps.semver.outputs.version }}" >> "$GITHUB_OUTPUT"
          fi
          
    outputs:
      needs: generate-semver
      env:
        semver: ${{ needs.generate-semver.semver }}
    steps:
      - name: debug
        run: echo "${{ needs.generate-semver.outputs.semver }}"
        