name: Nightly build
on:
  schedule:
    - cron: '0 0 * * *' 
  pull_request:
    types: [opened, edited, synchronize]
    branches: [main, development]
  workflow_dispatch:
  
jobs:
  build:
    uses: diogosilva96/workflow-templates/.github/workflows/dotnet-build-app.yml@main
    with:
      dotnet-version: '7.x.x'
      docker-publish: false
      docker-image-name: ds96/url-shortener-api
      environment: dev
      project-path: src/Url.Shortener.Api/Url.Shortener.Api.csproj
    secrets: inherit
